"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = "1.5.0"
__commit__ = "b88e9aa"
__version_full__ = "1.5.0+b88e9aa"
