"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = "1.1.0"
__commit__ = "8b04b43"
__version_full__ = "1.1.0+8b04b43"
