"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = "1.5.0"
__commit__ = "fe3bea5"
__version_full__ = "1.5.0+fe3bea5"
